version: 2
updates:
# GitHub Actions
- package-ecosystem: github-actions
  directory: .github/workflows
  schedule:
    interval: weekly
    day: wednesday
    time: '06:00'
    timezone: US/Eastern
  commit-message:
    prefix: â¬†
  labels:
  - maintenance ğŸ”§
  - CI ğŸ¦¾

# Helm charts
- package-ecosystem: helm
  directories: 
  - charts
  schedule:
    interval: weekly
    day: wednesday
    time: '06:00'
    timezone: US/Eastern
  commit-message:
    prefix: â¬†
  labels:
  - maintenance ğŸ”§
  - CD ğŸ—ï¸

# uv
- package-ecosystem: uv
  directory: docs
  schedule:
    interval: weekly
    day: wednesday
    time: '06:00'
    timezone: US/Eastern
  commit-message:
    prefix: â¬†
  labels:
  - maintenance ğŸ”§
  - documentation ğŸ“œ
  groups:
    mkdocs:
      patterns:
      - mkdocs*
