site_name: 'Open Vault: Deploy'
site_description: Open Vault redesign deployment documentation
site_url: https://wgbh-mla.github.io/ov-deploy/
repo_url: https://github.com/WGBH-MLA/ov-deploy/

nav:
  - Home: index.md
  - Setup: setup.md
  - Deploy: deploy.md
  - Guides: guides/index.md
  - Reference: reference.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      toc_depth: 4

theme:
  name: material
  logo: assets/ov-logo.png
  favicon: assets/ov-favicon.png

  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
  features:
    - content.code.annotate # Enable code annotations for a specific block
    - header.autohide # Hide header when scrolling
    - navigation.expanded # Expand all sections in sidebar by default
    - navigation.footer # Footer with navigation links
    - navigation.indexes # Combine index page with nav sidebar
    - navigation.instant # Load requests with XHR without reloading page
    - navigation.sections # Top level sections rendered as group in sidebar
    - navigation.tabs # Top level sections rendered as navbar
    - navigation.tabs.sticky # Tabs visible on scroll
    - navigation.top # Back to top button
    - navigation.tracking # Adds url#anchor to address bar
    - navigation.expand # Expand all collapsed sections by default
    - navigation.path # Show current path in nav bar
    - toc.follow # Highlight current section in table of contents
    # - toc.integrate # Nav bar is always rendered on the left
    - search.highlight # Highlight occurances in result when searching for a term
    - search.suggest # Suggest results in search
  custom_dir: overrides

plugins:
  - awesome-nav
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - glightbox
  - privacy
extra:
  social:
    - name: Open Vault - Demo
      icon: fontawesome/solid/vault
      link: http://ovfrontend.k8s.wgbhdigital.org/
    - name: GitHub repository
      icon: fontawesome/brands/github
      link: https://github.com/WGBH-MLA/ov-deploy/
  version:
    provider: mike

extra_css:
  - style/auth.css
  - style/gbh.css
  - style/github.css
  - style/kube.css
  - style/todo.css
  - style/traefik.css
