name: ğŸ“¦ Release
on:
  milestone:
    types: [closed]
jobs:
  release:
    name: ğŸ“¦ Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“ Create a release draft for a milestone
        id: create-release-milestone
        uses: ecampidoglio/auto-release-milestone@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: ğŸ–¨ï¸ Print the URL of the release draft
        if: steps.create-release-milestone.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
